### ISSUE TITLE
current atom mapping version doesn't handle the fused ring system correctly

### ISSUE THREAD

**Issue by shuail** [stxinsite/atom_mapping#1]
This issue was found by @finithstx on Jan 16 and after generating the map, it looks the current version of atom mapping could not handle the fused ring system correctly. Specifically, it looks like rdkit could not distinguish the bridging atoms vs non-bridging atoms in the fused ring. for more details, please check the uploaded files in this commit 0e1fe21323c9db626e2b18d81c6311bff7f5dcbc

**Comment by woodysherman** [comment]
@shuail , do you have a plan to address this? Comment here or we can discuss in the office.

**Comment by shuail** [comment]
This issue got improved by this commit 003c8d28334e058089c9fa6c46537e7813501687 , in the new V3 of mcss calculation the fused ring will be eliminated. Long termly, this is a bug in rdkit fused ring system, I reported a issue in the rdkti mailing list and Greg said that he will take a look into the source code and try to fix this.
